# Generated by Django 4.0.5 on 2022-06-16 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prode', '0004_forecast_delete_matchprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='forecast',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prode.player'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('player', 'match')},
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='user',
        ),
    ]
