# Generated by Django 4.0.5 on 2022-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0005_player_alter_forecast_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
