# Generated by Django 4.0.5 on 2022-06-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0007_tournament_alter_player_options_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_end',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
