# Generated by Django 4.0.5 on 2022-06-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0009_team_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
    ]
