# Generated by Django 4.0.5 on 2022-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0015_remove_match_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
